# Generated by Django 3.2 on 2021-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
